apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- ../../helm/namespaces/immich.yaml
- ../../helm/storage-classes/local-retain.yaml
- ../../helm/pvcs/immich.yaml
- ../../helm/flux-helm-repositories/immich.yaml
- ../../helm/flux-helm-releases/immich.yaml
