apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
# NAMESPACES
- ../../helm/namespaces/registry.yaml
- ../../helm/namespaces/cert-manager.yaml
# RELEASES
- ../../helm/flux-helm-releases/registry.yaml
- ../../helm/flux-helm-releases/cert-manager.yaml
