apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
# NAMESPACES
- ../../helm/namespaces/immich.yaml
- ../../helm/namespaces/cloudflare.yaml
- ../../helm/namespaces/postgresql.yaml
- ../../helm/namespaces/bitnami.yaml
# RELEASES
- ../../helm/flux-helm-releases/postgresql.yaml
#- ../../helm/flux-helm-releases/immich.yaml
#- ../../helm/flux-helm-releases/cloudflare_tunnel.yaml

