apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- ../../helm/flux-helm-releases/immich.yaml
- ../../helm/flux-helm-releases/nginx-helmrelease.yaml
- ../../helm/storage-classes/local-retain.yaml
