apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
# NAMESPACES
- ../../helm/namespaces/immich.yaml
# RELEASES
#- ../../helm/flux-helm-releases/immich.yaml
#- ../../helm/flux-helm-releases/cloudflare_tunnel.yaml

