apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: {{ .Values.secretStore.bitwardenSecretStore.apiURL }}
      identityURL: {{ .Values.secretStore.bitwardenSecretStore.identityURL }}
      auth:
        secretRef:
          credentials:
            key: {{ .Values.secretStore.bitwardenSecretStore.auth.secretRef.credentials.key }}
            name: {{ .Values.secretStore.bitwardenSecretStore.auth.secretRef.credentials.name }}
      bitwardenServerSDKURL: {{ .Values.secretStore.bitwardenSecretStore.bitwardenServerSDKURL }}
      caBundle: {{ .Values.secretStore.bitwardenSecretStore.caBundle | quote }}
      organizationID: {{ .Values.secretStore.bitwardenSecretStore.organizationID }}
      projectID: {{ .Values.secretStore.bitwardenSecretStore.projectID }}