apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-tls
  namespace: external-secrets
spec:
  secretName: bitwarden-tls-certs
  duration: 8760h
  renewBefore: 360h
  commonName: bitwarden-sdk-server.external-secrets.svc.cluster.local
  dnsNames:
    - bitwarden-sdk-server.external-secrets.svc.cluster.local
  issuerRef:
    name: selfsigned-clusterissuer
    kind: ClusterIssuer
