apiVersion: v1
kind: Service
metadata:
  name: digipiggy
  namespace: {{ .Values.digipiggy.namespace }}
spec:
  type: {{ .Values.digipiggy.service.type }}
  ports:
    - port: {{ .Values.digipiggy.service.port }}
      targetPort: {{ .Values.digipiggy.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: digipiggy

