apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgvecto-rs
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgvecto-rs
  template:
    metadata:
      labels:
        app: pgvecto-rs
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.user }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.database }}"
            - name: POSTGRES_INITDB_ARGS
              value: "{{ .Values.postgres.dataChecksum }}"
          command: [
            "postgres",
            "-c", "shared_preload_libraries=vectors.so",
            "-c", "search_path=$$user, public, vectors",
            "-c", "logging_collector=on",
            "-c", "max_wal_size=2GB",
            "-c", "shared_buffers=512MB",
            "-c", "wal_compression=on"
          ]
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pgvecto-rs-pvc
