apiVersion: v2
name: minio
description: A Helm chart for MinIO object storage
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: minio
    version: 17.0.15
    repository: https://charts.bitnami.com/bitnami 