# MinIO Configuration
namespace: minio
minio:
  enabled: true
  auth:
    existingSecret: minio-secret
    secretKeys:
      rootUserKey: root-user
      rootPasswordKey: root-password
  service:
    type: ClusterIP
    port: 9000
  api:
    service:
      type: ClusterIP
      port: 9000
  console:
    service:
      type: ClusterIP
      port: 9001
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  # Create default bucket for equilink
  defaultBuckets: "equilink-files"
  # Enable metrics
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false 