apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  data:
  - secretKey: token
    remoteRef:
      key: {{ .Values.bitwardenTokenRef }} 