apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudflare-tunnel.selectorLabels" . | nindent 4 }} 