apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: equilink
  namespace: equilink
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/charts/equilink
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system