apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: immich
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/charts/immich
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system