apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 16.6.6
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: bitnami
  values:
    image:
      tag: 17.4.0
    