apiVersion: v2
name: postgresql
description: A simple postgresql deployment
version: 0.1.0
dependencies:
  - name: postgresql
    version: 16.6.6
    repository: oci://registry-1.docker.io/bitnamicharts