namespace: postgresql

postgresql:
  image:
    registry: docker.io
    repository: tensorchord/pgvecto-rs
    tag: pg17-v0.0.0-nightly.20250227
    debug: true

  auth:
    database: immich
    username: immich
    password: TODO

  primary:
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsNonRoot: true
      allowPrivilegeEscalation: false

    podSecurityContext:
      enabled: true
      fsGroup: 1001

    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=vectors.so"
      - "-c"
      - "search_path='$user', public, vectors"
      - "-c"
      - "logging_collector=on"

    initdb:
      args: "--data-checksums"
      scripts:
        enable_vectors.sql: |
          CREATE EXTENSION vectors;

    persistence:
      enabled: true
      size: 8Gi
      storageClass: ""  # Set this if needed

    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m

  volumePermissions:
    enabled: true

global:
  storageClass: ""
  security:
    allowInsecureImages: true
