namespace: postgresql

postgresql:
  image:
    registry: docker.io
    repository: tensorchord/pgvecto-rs
    tag: pg17-v0.0.0-nightly.20250227

  primary:
    initdb:
      scripts:
        enable_vectors.sql: |
          CREATE EXTENSION vectors;

    persistence:
      size: 8Gi
      mountPath: /var/lib/postgresql/data

    extraEnvVars:
      - name: PGDATA
        value: /var/lib/postgresql/data
      - name: PGSOCKET_DIR
        value: /tmp

    extraVolumes:
      - name: postgresql-run
        emptyDir: {}
      - name: postgresql-log
        emptyDir: {}

    extraVolumeMounts:
      - name: postgresql-run
        mountPath: /var/run/postgresql
      - name: postgresql-log
        mountPath: /var/log/postgresql

  auth:
    database: immich
    username: immich
    password: TODO

  volumePermissions:
    enabled: true

global:
  security:
    allowInsecureImages: true
