namespace: postgresql

postgresql:
  primary:
    initdb:
      scripts:
        enable_vectors.sql: |
          CREATE EXTENSION vectors;
    persistence:
      size: 8Gi
  image:
    registry: docker.io
    repository: tensorchord/pgvecto-rs
    tag: pg17-v0.0.0-nightly.20250227

  auth:
    database: immich
    username: immich
    password: TODO

  global:
    security:
      allowInsecureImages: true
