namespace: postgresql

postgresql:
  primary:
    initdb:
      scripts:
        enable_vectors.sql: |
          CREATE EXTENSION vectors;
    persistence:
      size: 8Gi
    securityContext:
      enabled: true
      fsGroup: 1001
      runAsUser: 1001
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsNonRoot: true
    podSecurityContext:
      enabled: true
      fsGroup: 1001
    extraEnvVars:
      - name: PGDATA
        value: /bitnami/postgresql/data
      - name: PGSOCKET_DIR
        value: /tmp
  image:
    registry: docker.io
    repository: tensorchord/pgvecto-rs
    tag: pg17-v0.0.0-nightly.20250227

  auth:
    database: immich
    username: immich
    password: TODO

  global:
    security:
      allowInsecureImages: true

  volumePermissions:
    enabled: true
