namespace: postgresql

postgresql:
  image:
    registry: docker.io
    repository: tensorchord/pgvecto-rs
    tag: pg17-v0.0.0-nightly.20250227

  primary:
    initdb:
      scripts:
        enable_vectors.sql: |
          CREATE EXTENSION vectors;

    persistence:
      size: 8Gi

  auth:
    database: immich
    username: immich
    password: TODO


global:
  security:
    allowInsecureImages: true
