namespace: postgresql

postgresql:
  primary:
    initdb:
      scripts: |
          CREATE EXTENSION vectors;
        
    persistence:
      size: 8Gi
  image:
    tag: 17.4.0

  global:
    auth:
      database: immich
      username: immich
      password: TODO
