apiVersion: v2
name: cloudflare-tunnel
description: A Helm chart for Cloudflare Tunnel deployment with external secrets integration
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - cloudflare
  - tunnel
  - networking
  - proxy
