apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
      