apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}