apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }} 