apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: equilink
spec:
  refreshInterval: 1h
  secretStoreRef:
    # This name must match the metadata.name in the `SecretStore`
    name: bitwarden-secret-store
    kind: ClusterSecretStore
  target:
    name: equilink
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: "c0b14e33-df03-4ea5-8291-b32700de20e0"