apiVersion: v2
name: external-secrets
description: Deployment of external-secrets https://external-secrets.io/
version: 0.1.0
dependencies:
  - name: external-secrets
    version: 0.18.2
    repository: https://charts.external-secrets.io